import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
assert.match(css, /\.admin-shell \.header-inner,\.learner-shell \.header-inner\{min-height:56px;display:flex;padding-top:0\}/);
assert.match(css, /\.admin-shell \.brand img,\.learner-shell \.brand img\{width:72px;height:auto\}/);
assert.match(css, /\.learner-shell \.header-inner\{min-height:64px\}/);
assert.match(css, /\.nav button\{min-height:44px\}/);
assert.match(css, /padding-bottom:6rem/);
assert.match(css, /padding-bottom:max\(\.35rem,env\(safe-area-inset-bottom\)\)/);
console.log('navbar contracts OK');
